//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSICEForm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestSICEForm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Peaje&gt;
        ///	&lt;Numero_consecutivo_envio&gt;1&lt;/Numero_consecutivo_envio&gt;
        ///	&lt;Numero_registros&gt;45&lt;/Numero_registros&gt;
        ///	&lt;Hora_envio&gt;00:01:11&lt;/Hora_envio&gt;
        ///	&lt;Fecha_envio&gt;17-10-2024&lt;/Fecha_envio&gt;
        ///	&lt;Registro&gt;
        ///		&lt;Numero_TAG&gt;VPAS00616314&lt;/Numero_TAG&gt;
        ///		&lt;Concesion&gt;25&lt;/Concesion&gt;
        ///		&lt;Tipo_TAG&gt;1&lt;/Tipo_TAG&gt;
        ///		&lt;IUT&gt;001014010A1016225344161020246&lt;/IUT&gt;
        ///		&lt;Categoria&gt;13&lt;/Categoria&gt;
        ///		&lt;Categoria_Cobrada&gt;13&lt;/Categoria_Cobrada&gt;
        ///		&lt;Categoria_Detectada&gt;13&lt;/Categoria_Detectada&gt;
        ///		&lt;Status&gt;1&lt;/Status&gt;
        ///		&lt;Ho [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string V00000117102024000111 {
            get {
                return ResourceManager.GetString("V00000117102024000111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Peaje&gt;
        ///	&lt;Numero_consecutivo_envio&gt;30&lt;/Numero_consecutivo_envio&gt;
        ///	&lt;Numero_registros&gt;12&lt;/Numero_registros&gt;
        ///	&lt;Hora_envio&gt;01:00:20&lt;/Hora_envio&gt;
        ///	&lt;Fecha_envio&gt;17-10-2024&lt;/Fecha_envio&gt;
        ///	&lt;Registro&gt;
        ///		&lt;Numero_TAG&gt;VPAS00662016&lt;/Numero_TAG&gt;
        ///		&lt;Concesion&gt;25&lt;/Concesion&gt;
        ///		&lt;Tipo_TAG&gt;1&lt;/Tipo_TAG&gt;
        ///		&lt;IUT&gt;005003005B1017005735171020245&lt;/IUT&gt;
        ///		&lt;Categoria&gt;9&lt;/Categoria&gt;
        ///		&lt;Categoria_Cobrada&gt;9&lt;/Categoria_Cobrada&gt;
        ///		&lt;Categoria_Detectada&gt;9&lt;/Categoria_Detectada&gt;
        ///		&lt;Status&gt;1&lt;/Status&gt;
        ///		&lt;Hora [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string V00003017102024010020 {
            get {
                return ResourceManager.GetString("V00003017102024010020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Peaje&gt;
        ///	&lt;Numero_consecutivo_envio&gt;60&lt;/Numero_consecutivo_envio&gt;
        ///	&lt;Numero_registros&gt;8&lt;/Numero_registros&gt;
        ///	&lt;Hora_envio&gt;02:00:07&lt;/Hora_envio&gt;
        ///	&lt;Fecha_envio&gt;17-10-2024&lt;/Fecha_envio&gt;
        ///	&lt;Registro&gt;
        ///		&lt;Numero_TAG&gt;VPAS00662374&lt;/Numero_TAG&gt;
        ///		&lt;Concesion&gt;25&lt;/Concesion&gt;
        ///		&lt;Tipo_TAG&gt;1&lt;/Tipo_TAG&gt;
        ///		&lt;IUT&gt;005088012A1017015713171020246&lt;/IUT&gt;
        ///		&lt;Categoria&gt;9&lt;/Categoria&gt;
        ///		&lt;Categoria_Cobrada&gt;9&lt;/Categoria_Cobrada&gt;
        ///		&lt;Categoria_Detectada&gt;9&lt;/Categoria_Detectada&gt;
        ///		&lt;Status&gt;1&lt;/Status&gt;
        ///		&lt;Hora_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string V00006017102024020007 {
            get {
                return ResourceManager.GetString("V00006017102024020007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Peaje&gt;
        ///	&lt;Numero_consecutivo_envio&gt;90&lt;/Numero_consecutivo_envio&gt;
        ///	&lt;Numero_registros&gt;9&lt;/Numero_registros&gt;
        ///	&lt;Hora_envio&gt;03:00:21&lt;/Hora_envio&gt;
        ///	&lt;Fecha_envio&gt;17-10-2024&lt;/Fecha_envio&gt;
        ///	&lt;Registro&gt;
        ///		&lt;Numero_TAG&gt;VPAS00668047&lt;/Numero_TAG&gt;
        ///		&lt;Concesion&gt;25&lt;/Concesion&gt;
        ///		&lt;Tipo_TAG&gt;1&lt;/Tipo_TAG&gt;
        ///		&lt;IUT&gt;005004018A1017025808171020245&lt;/IUT&gt;
        ///		&lt;Categoria&gt;9&lt;/Categoria&gt;
        ///		&lt;Categoria_Cobrada&gt;9&lt;/Categoria_Cobrada&gt;
        ///		&lt;Categoria_Detectada&gt;9&lt;/Categoria_Detectada&gt;
        ///		&lt;Status&gt;1&lt;/Status&gt;
        ///		&lt;Hora_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string V00009017102024030021 {
            get {
                return ResourceManager.GetString("V00009017102024030021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Peaje&gt;
        ///	&lt;Numero_consecutivo_envio&gt;120&lt;/Numero_consecutivo_envio&gt;
        ///	&lt;Numero_registros&gt;9&lt;/Numero_registros&gt;
        ///	&lt;Hora_envio&gt;04:00:08&lt;/Hora_envio&gt;
        ///	&lt;Fecha_envio&gt;17-10-2024&lt;/Fecha_envio&gt;
        ///	&lt;Registro&gt;
        ///		&lt;Numero_TAG&gt;VPAS00227355&lt;/Numero_TAG&gt;
        ///		&lt;Concesion&gt;25&lt;/Concesion&gt;
        ///		&lt;Tipo_TAG&gt;1&lt;/Tipo_TAG&gt;
        ///		&lt;IUT&gt;005003010A1017035827171020246&lt;/IUT&gt;
        ///		&lt;Categoria&gt;6&lt;/Categoria&gt;
        ///		&lt;Categoria_Cobrada&gt;6&lt;/Categoria_Cobrada&gt;
        ///		&lt;Categoria_Detectada&gt;6&lt;/Categoria_Detectada&gt;
        ///		&lt;Status&gt;1&lt;/Status&gt;
        ///		&lt;Hora [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string V00012017102024040008 {
            get {
                return ResourceManager.GetString("V00012017102024040008", resourceCulture);
            }
        }
    }
}
